markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Aaron Wong
url: http://aaron.xghk.net
description: 
email: aaron.ym.wong@gmail.com 
linkedin: aaronymwong

theme: jekyll-theme-minimal